<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNZ2BS6g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNZ2BS6g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNZ2BS6g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNZ2BS6g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNZ2BS6g\App_KernelDevDebugContainer([
    'container.build_hash' => 'NZ2BS6g',
    'container.build_id' => '3d598cbc',
    'container.build_time' => 1625820347,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNZ2BS6g');
