<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYOLJdFa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYOLJdFa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYOLJdFa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYOLJdFa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYOLJdFa\App_KernelDevDebugContainer([
    'container.build_hash' => 'YOLJdFa',
    'container.build_id' => '63158cc9',
    'container.build_time' => 1626938323,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYOLJdFa');
